'use strict';

const root=document.documentElement;
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
const storage={get(k){try{return localStorage.getItem(k)}catch{return null}},set(k,v){try{localStorage.setItem(k,v)}catch{}}};
let lang=storage.get('lang')==='en'?'en':'tr';
let activeCase=null;
let caseTrigger=null;
const languageButton=document.getElementById('language');
const dialog=document.getElementById('case-dialog');

const CASE_STUDIES={
  kanyolda:{title:'KanYolda',image:'assets/projects/kanyolda.jpg',alt:{tr:'KanYolda web ve mobil ürün ekranı',en:'KanYolda web and mobile product screen'},category:{tr:'Mobil ürün · Web platformu',en:'Mobile product · Web platform'},summary:{tr:'Kan ihtiyacı olanları uygun donörlerle konum, kan grubu ve aciliyet üzerinden buluşturan uçtan uca ürün.',en:'An end-to-end product matching urgent blood needs with suitable donors by location, blood type and priority.'},facts:{tr:[['Rol','Ürün ve yazılım geliştirme'],['Yıl','2026'],['Platform','Mobil + Web'],['Altyapı','Next.js · React Native · Firebase']],en:[['Role','Product and software development'],['Year','2026'],['Platform','Mobile + Web'],['Stack','Next.js · React Native · Firebase']]},problem:{tr:'Acil kan ihtiyacında ilanların dağınık kanallarda paylaşılması, uygun donöre ulaşmayı yavaşlatıyor. Kullanıcının hem yakınındaki ihtiyacı görmesi hem de güvenli biçimde iletişim kurabilmesi gerekiyordu.',en:'During urgent blood needs, requests are spread across disconnected channels. The product needed to help people find nearby requests and communicate safely.'},approach:{tr:'İlan, eşleştirme, konum, bildirim ve sohbet akışlarını tek ürün modeli altında topladım. Mobil deneyimi donörün hızlı aksiyon almasına; web ve yönetim tarafını ise ilanların doğrulanması ve yönetilmesine göre kurguladım.',en:'I brought requests, matching, location, notifications and chat into one product model. Mobile supports fast donor action, while web and admin flows focus on request verification and management.'},result:{tr:'Şehir ve kan grubuna göre otomatik eşleştirme yapan, acil bildirim gönderen, harita ve sohbet özellikleri bulunan mobil/web platformu ortaya çıktı.',en:'The result is a mobile and web platform with city and blood-type matching, urgent notifications, map features and chat.'},decisions:{tr:['Mobil ve web istemcilerinde ortak Firebase veri modeli','Acil ilanlar için kan grubu ve konum temelli eşleştirme','Bildirim, sohbet ve harita akışlarının aynı kullanıcı yolculuğunda birleşmesi','Yönetim panelinde ilan ve kullanıcı denetimi'],en:['Shared Firebase data model across mobile and web','Blood-type and location matching for urgent requests','Notifications, chat and map within one user journey','Request and user moderation in the admin panel']},links:[{type:'live',href:'https://www.kanyolda.com.tr/'}]},
  sinaru:{title:'Sinaru',image:'assets/projects/sinaru.jpg',alt:{tr:'Sinaru çevrimdışı bilgi asistanı ekranı',en:'Sinaru offline knowledge assistant screen'},category:{tr:'Yerel yapay zekâ · RAG',en:'Local artificial intelligence · RAG'},summary:{tr:'Belgeleri cihaz üzerinde indeksleyen, semantik olarak arayan ve cevabı kullandığı kaynaklarla birlikte veren çevrimdışı asistan.',en:'An offline assistant that indexes documents on-device, searches them semantically and returns answers with the sources it used.'},facts:{tr:[['Rol','Mimari, backend ve arayüz'],['Yıl','2026'],['Çalışma','%100 yerel'],['Altyapı','Node.js · Foundry Local · SQLite']],en:[['Role','Architecture, backend and interface'],['Year','2026'],['Runtime','100% local'],['Stack','Node.js · Foundry Local · SQLite']]},problem:{tr:'Hassas veya kurumsal belgeler bulut tabanlı yapay zekâ servislerine gönderilmeden aranmalı ve soru-cevap için kullanılmalıydı. Üretilen cevabın hangi metne dayandığı da görünür olmalıydı.',en:'Sensitive documents needed to be searched and queried without sending them to cloud AI services. The source text behind every generated answer also had to stay visible.'},approach:{tr:'Belgeleri parçalayıp yerel embedding modeliyle 1024 boyutlu vektörlere dönüştürdüm. Vektörleri SQLite içinde saklayıp kosinüs benzerliğiyle aradım; en ilgili parçaları yerel dil modeline bağlam olarak verip cevabı SSE ile akıttım.',en:'I chunked documents, converted them into 1024-dimensional vectors with a local embedding model, stored them in SQLite, searched by cosine similarity and streamed grounded answers over SSE.'},result:{tr:'Doküman yükleme, sohbet geçmişi, kaynak kartları, istatistikler, komut paleti ve TR/EN desteği olan, internet olmadan çalışan bir RAG ürünü oluştu.',en:'The result is an offline RAG product with document upload, conversation history, source cards, analytics, a command palette and TR/EN support.'},decisions:{tr:['Foundry Local ile cihaz üstünde model çalıştırma','Embedding vektörlerini aynı SQLite tablosunda BLOB olarak saklama','Kaynak parçasını ve güven skorunu cevap yanında gösterme','Yanıtı SSE ile gerçek zamanlı aktarma','Ağ veya model gerektirmeyen kapsamlı test seti'],en:['On-device inference with Foundry Local','Embedding vectors stored as BLOBs in SQLite','Source chunks and relevance scores shown beside answers','Real-time response streaming over SSE','Comprehensive tests that require no network or model']},links:[{type:'code',href:'https://github.com/arincakyildiz/RAG-Application-with-Foundry-Local'}]},
  perfiai:{title:'PerfiAI',image:'assets/projects/perfiai.png',alt:{tr:'PerfiAI marka görseli',en:'PerfiAI brand visual'},category:{tr:'Anlamsal arama · Öneri sistemi',en:'Semantic search · Recommendation system'},summary:{tr:'Kullanıcının doğal dille tarif ettiği kokuyu 26.000 parfümlük katalogda arayan; sonucu skor, gerekçe ve etiketlerle açıklayan öneri sistemi.',en:'A recommendation system that searches a 26,000-fragrance catalogue from a natural-language description and explains each result with a score, reason and tags.'},facts:{tr:[['Rol','Full-stack ve AI entegrasyonu'],['Yıl','2026'],['Katalog','26.000 parfüm'],['Altyapı','Next.js · Express · FastAPI · SentenceTransformers']],en:[['Role','Full-stack and AI integration'],['Year','2026'],['Catalogue','26,000 fragrances'],['Stack','Next.js · Express · FastAPI · SentenceTransformers']]},problem:{tr:'Klasik parfüm filtreleri marka veya nota göre çalışıyor; kullanıcı ise çoğu zaman “ferah narenciye, yazın ofise uygun” gibi doğal bir tarifle arama yapıyor. 26.000 ürün içinde bu niyeti doğru yorumlamak ve sonucu nedenleriyle açıklamak gerekiyordu.',en:'Traditional fragrance filters operate by brand or note, while people often search with phrases such as “fresh citrus for a summer office”. The product needed to interpret that intent across 26,000 items and explain every match.'},approach:{tr:'Nota piramitleri, akorlar, mevsim, cinsiyet ve açıklamaları ortak bir arama temsiline dönüştürdüm. Sistem sezgisel modda her ortamda çalışıyor; yerel SentenceTransformers servisi açıldığında float16 embedding indeksi üzerinden kosinüs benzerliğine geçiyor.',en:'I combined note pyramids, accords, season, gender and descriptions into one search representation. A heuristic mode works everywhere; when the local SentenceTransformers service is available, search switches to cosine similarity over a float16 embedding index.'},result:{tr:'Doğal dil araması, filtreler, açıklanabilir skorlar, üyelik, e-posta doğrulama, favoriler, puanlar ve yorumları birleştiren iki dilli parfüm keşif ürünü ortaya çıktı.',en:'The result is a bilingual fragrance-discovery product combining natural-language search, filters, explainable scores, accounts, email verification, favourites, ratings and comments.'},decisions:{tr:['26.000 kayıt için float16 embedding indeksi','SentenceTransformers servisi yoksa sezgisel arama yedeği','Her sonuçta skor, eşleşme gerekçesi ve etiketler','MongoDB veya atomik JSON kalıcılığı','10×10 WebP atlasları ve markalı fallback kartları','Tekrar çalıştırılabilir veri hattı'],en:['Float16 embedding index for 26,000 records','Heuristic fallback without SentenceTransformers','Score, reason and tags on every result','MongoDB or atomic JSON persistence','10×10 WebP atlases and branded fallback cards','Reproducible data pipeline']},links:[{type:'profile',href:'https://github.com/arincakyildiz'}]},
  keyco:{title:'Keyco',image:'assets/projects/keyco.jpg',alt:{tr:'Keyco e-ticaret ürün ekranı',en:'Keyco e-commerce product screen'},category:{tr:'E-ticaret · Web uygulaması',en:'E-commerce · Web application'},summary:{tr:'Oyun kodları ve dijital ürünler için keşif, kategori, hesap ve satın alma akışlarını bir araya getiren e-ticaret uygulaması.',en:'An e-commerce application bringing together discovery, category, account and purchase flows for game keys and digital products.'},facts:{tr:[['Rol','Full-stack geliştirme'],['Yıl','2025'],['Platform','Web'],['Altyapı','React · Node.js · Firebase']],en:[['Role','Full-stack development'],['Year','2025'],['Platform','Web'],['Stack','React · Node.js · Firebase']]},problem:{tr:'Farklı oyun platformlarındaki dijital ürünlerin hızlı bulunması, kategori ve platforma göre filtrelenmesi ve güvenli bir satın alma akışına taşınması gerekiyordu.',en:'Digital products across gaming platforms needed to be easy to discover, filter by category and platform, and move through a clear purchase flow.'},approach:{tr:'Kataloğu platform ve kategori etrafında düzenledim; arama, filtreleme, üyelik ve ödeme adımlarını tek kullanıcı yolculuğu içinde kurdum.',en:'I structured the catalogue around platforms and categories, then connected search, filtering, accounts and payment into one user journey.'},result:{tr:'Dijital ürün keşfi, hesap yönetimi ve ödeme entegrasyonlarını destekleyen, iki dilli ve farklı ekranlara uyumlu bir mağaza deneyimi oluştu.',en:'The result is a responsive, bilingual store experience supporting digital product discovery, account management and payment integrations.'},decisions:{tr:['Platform ve kategori bazlı ürün taksonomisi','Arama ve filtre durumunun tek ürün listesinde birleşmesi','Üyelik ve sipariş akışlarında Firebase','Kalıcı TR/EN dil ve tema tercihi'],en:['Platform and category product taxonomy','Combined search and filter state','Firebase for accounts and orders','Persistent TR/EN language and theme preference']},links:[{type:'live',href:'https://keyco.vercel.app'},{type:'code',href:'https://github.com/arincakyildiz/keyco'}]}
};

const OTHER_PROJECTS={
  kargo:{title:'Kargo Takip',year:'2026',category:{tr:'Operasyon · Web uygulaması',en:'Operations · Web application'},description:{tr:'Kargo hareketleri ve operasyon adımlarını izlemek için geliştirilen Angular tabanlı takip arayüzü.',en:'An Angular-based tracking interface for following cargo movements and operational steps.'},tech:['Angular','TypeScript','RxJS'],links:[{type:'live',href:'https://kargotakip.arincakyildiz.com.tr/'},{type:'code',href:'https://github.com/arincakyildiz/kargo-project'}]},
  wavent:{title:'Wavent',year:'2026',category:{tr:'Depo yönetimi · Web uygulaması',en:'Warehouse management · Web application'},description:{tr:'Envanter ve depo operasyonlarını yönetmek için tasarlanan modüler kullanıcı arayüzü.',en:'A modular interface designed to manage inventory and warehouse operations.'},tech:['Angular','TypeScript','WMS'],links:[{type:'live',href:'https://wavent-zeta.vercel.app'},{type:'code',href:'https://github.com/arincakyildiz/wavent'}]},
  roadnix:{title:'Roadnix',year:'2025',category:{tr:'Eğitim · Web platformu',en:'Education · Web platform'},description:{tr:'Trafik güvenliğini etkileşimli içerikler, testler ve görsel anlatımla öğreten eğitim platformu.',en:'An educational platform teaching road safety through interactive content, tests and visual explanations.'},tech:['React','Vite','JavaScript'],links:[{type:'live',href:'https://roadnix.arincakyildiz.com.tr/'},{type:'code',href:'https://github.com/arincakyildiz/roadnix'}]},
  eventify:{title:'Eventify TRNC',year:'2025',category:{tr:'Etkinlik · Keşif platformu',en:'Events · Discovery platform'},description:{tr:'Kuzey Kıbrıs’taki etkinlikleri tek yerde keşfetmek ve takip etmek için geliştirilen web uygulaması.',en:'A web application for discovering and following events across Northern Cyprus.'},tech:['Node.js','JavaScript','Web'],links:[{type:'live',href:'https://eventify-trnc.vercel.app'},{type:'code',href:'https://github.com/arincakyildiz/Eventify-TRNC'}]},
  emurebook:{title:'Emu Rebook',year:'2024',category:{tr:'Mobil · Kampüs uygulaması',en:'Mobile · Campus application'},description:{tr:'Flutter ve Dart ile geliştirilen, öğrenciler için mobil kampüs ve kitap deneyimi.',en:'A mobile campus and book experience for students, built with Flutter and Dart.'},tech:['Flutter','Dart','Mobile'],links:[{type:'code',href:'https://github.com/arincakyildiz/emurebook'}]},
  kofteci:{title:'Tarihi Sanayi Köftecisi',year:'2024',category:{tr:'Web sitesi · Yerel işletme',en:'Website · Local business'},description:{tr:'Restoranın hikâyesini, menüsünü ve iletişim bilgilerini yalın bir deneyimde sunan web sitesi.',en:'A website presenting the restaurant’s story, menu and contact details in a clear experience.'},tech:['HTML','CSS','JavaScript'],links:[{type:'live',href:'https://tarihisanayikoftecisi.arincakyildiz.com.tr/'},{type:'code',href:'https://github.com/arincakyildiz/tarihi-sanayi-koftecisi'}]}
};

const t=key=>window.TRANSLATIONS[lang]?.[key]??key;
const lineElements=()=>[...document.querySelectorAll('[data-i18n-lines]')];
function buildLine(element,lines){element.replaceChildren(...lines.map(text=>{const outer=document.createElement('span');const inner=document.createElement('i');inner.textContent=text;outer.append(inner);return outer}))}
function buildWords(element,text){element.replaceChildren(...text.split(' ').flatMap((word,index)=>{const span=document.createElement('span');span.className='word';span.style.transitionDelay=`${index*35}ms`;span.textContent=word;return index?[document.createTextNode(' '),span]:[span]}))}
function applyLanguage(){
  root.lang=lang;
  document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));
  lineElements().forEach(el=>{buildLine(el,t(el.dataset.i18nLines));if((el.id==='hero-title'&&document.body.classList.contains('ready'))||el.classList.contains('is-visible'))requestAnimationFrame(()=>playLines(el))});
  document.querySelectorAll('.word-reveal[data-i18n]').forEach(el=>buildWords(el,t(el.dataset.i18n)));
  languageButton.textContent=lang==='tr'?'EN':'TR';languageButton.setAttribute('aria-label',lang==='tr'?'Switch to English':'Türkçeye geç');
  document.title=lang==='tr'?'Ahmet Arınç Akyıldız — Yazılım Mühendisi':'Ahmet Arınç Akyıldız — Software Engineer';
  if(activeCase)renderCase(activeCase);renderHeroCard(false);renderCarouselInfo(false);
}

function applyAdaptiveGrid(){const size=16-(16*(((1920-innerWidth)/1920)*100*.6666))/100;if(size>16)root.style.fontSize=`${size}px`;else root.style.removeProperty('font-size')}
addEventListener('resize',applyAdaptiveGrid);applyAdaptiveGrid();

const lock=()=>document.body.classList.add('locked');
const unlock=()=>{if(!document.querySelector('.nav-menu.open')&&!document.querySelector('.contact-modal.open')&&!dialog.open)document.body.classList.remove('locked')};

function startLoader(){
  const loader=document.querySelector('.page-loader');
  if(reducedMotion.matches){loader.remove();document.body.classList.add('ready');return}
  lock();const fill=loader.querySelector('.loader-progress b');const counter=loader.querySelector('.loader-progress strong');const start=performance.now();
  function tick(now){const raw=Math.min(1,(now-start)/1300);const eased=raw<.5?4*raw**3:1-((-2*raw+2)**3)/2;const value=Math.round(eased*100);fill.style.width=`${value}%`;counter.textContent=String(value).padStart(3,'0');if(raw<1)requestAnimationFrame(tick);else{loader.classList.add('leaving');document.body.classList.add('ready');setTimeout(()=>{loader.remove();unlock();playHeroLines()},760)}}requestAnimationFrame(tick)
}

function playLines(element){element.querySelectorAll(':scope>span>i').forEach((line,index)=>{line.style.transition=`transform .9s cubic-bezier(.215,.61,.355,1) ${index*110}ms,opacity .7s ease ${index*110}ms`;requestAnimationFrame(()=>{line.style.transform='translateY(0)';line.style.opacity='1'})})}
function playHeroLines(){playLines(document.getElementById('hero-title'))}

const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('is-visible');if(entry.target.classList.contains('line-reveal'))playLines(entry.target);revealObserver.unobserve(entry.target)}),{threshold:.12,rootMargin:'0px 0px -6%'});
document.querySelectorAll('.reveal,.word-reveal,.line-reveal:not(#hero-title)').forEach((el,index)=>{if(el.classList.contains('reveal'))el.style.transitionDelay=`${Math.min(index%4,3)*65}ms`;revealObserver.observe(el)});

const heroCards={tr:[['Mobil ürün','Gerçek ihtiyaca çözüm.'],['Yerel yapay zekâ','Veri cihazda kalır.'],['Ürün sistemleri','Uçtan uca geliştirilir.']],en:[['Mobile product','Solving a real need.'],['Local artificial intelligence','Data stays on-device.'],['Product systems','Built end to end.']]};
let heroCardIndex=0;
function renderHeroCard(animate=true){const [caption,title]=heroCards[lang][heroCardIndex];const a=document.getElementById('hero-card-caption');const b=document.getElementById('hero-card-title');if(animate&&!reducedMotion.matches){[a,b].forEach((el,i)=>el.animate([{opacity:0,transform:'translateY(12px)'},{opacity:1,transform:'translateY(0)'}],{duration:420,delay:i*55,easing:'cubic-bezier(.16,1,.3,1)'}))}a.textContent=caption;b.textContent=title;document.querySelectorAll('.card-dots i').forEach((dot,i)=>dot.classList.toggle('active',i===heroCardIndex))}
document.getElementById('hero-card-next').addEventListener('click',()=>{heroCardIndex=(heroCardIndex+1)%3;renderHeroCard()});
document.getElementById('hero-card-prev').addEventListener('click',event=>{event.stopPropagation();heroCardIndex=(heroCardIndex+2)%3;renderHeroCard()});

function updateClock(){const now=new Date();document.getElementById('clock-time').textContent=new Intl.DateTimeFormat(lang==='tr'?'tr-TR':'en-GB',{hour:'2-digit',minute:'2-digit',hour12:false,timeZone:'Europe/Istanbul'}).format(now);document.getElementById('clock-date').textContent=new Intl.DateTimeFormat(lang==='tr'?'tr-TR':'en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'Europe/Istanbul'}).format(now);document.getElementById('menu-clock').textContent=document.getElementById('clock-time').textContent}
setInterval(updateClock,1000);updateClock();

document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{const target=document.querySelector(link.hash);if(!target)return;event.preventDefault();target.scrollIntoView({behavior:reducedMotion.matches?'auto':'smooth'})}));
languageButton.addEventListener('click',()=>{lang=lang==='tr'?'en':'tr';storage.set('lang',lang);applyLanguage();updateClock()});

const menu=document.getElementById('nav-menu');
function openMenu(){menu.hidden=false;lock();requestAnimationFrame(()=>menu.classList.add('open'));document.getElementById('menu-open').setAttribute('aria-expanded','true')}
function closeMenu(unlockPage=true){menu.classList.remove('open');document.getElementById('menu-open').setAttribute('aria-expanded','false');setTimeout(()=>{menu.hidden=true;if(unlockPage)unlock()},450)}
document.getElementById('menu-open').addEventListener('click',openMenu);document.getElementById('menu-close').addEventListener('click',()=>closeMenu());
menu.querySelectorAll('[data-target]').forEach(button=>button.addEventListener('click',()=>{const id=button.dataset.target;closeMenu();setTimeout(()=>document.getElementById(id)?.scrollIntoView({behavior:'smooth'}),460)}));

const contactModal=document.getElementById('contact-modal');
function openContact(){if(menu.classList.contains('open'))closeMenu(false);contactModal.hidden=false;lock();requestAnimationFrame(()=>contactModal.classList.add('open'));setTimeout(()=>contactModal.querySelector('input')?.focus(),450)}
function closeContact(){contactModal.classList.remove('open');setTimeout(()=>{contactModal.hidden=true;unlock()},360)}
document.querySelectorAll('[data-contact]').forEach(button=>button.addEventListener('click',openContact));document.getElementById('contact-close').addEventListener('click',closeContact);contactModal.addEventListener('click',event=>{if(event.target===contactModal)closeContact()});
document.getElementById('contact-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const subject=encodeURIComponent(`${data.get('name')} — Portfolio contact`);const body=encodeURIComponent(`${data.get('message')}\n\n${data.get('name')}\n${data.get('email')}`);location.href=`mailto:ahmetarincakyildiz@gmail.com?subject=${subject}&body=${body}`});
document.getElementById('copy-email').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('ahmetarincakyildiz@gmail.com');document.getElementById('copy-status').textContent=t('contact.copied')}catch{document.getElementById('copy-status').textContent='ahmetarincakyildiz@gmail.com'}});
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if(contactModal.classList.contains('open'))closeContact();else if(menu.classList.contains('open'))closeMenu()});

function setupLiquidReveal(){
  if(reducedMotion.matches)return;
  const host=document.querySelector('.liquid-reveal');const canvas=host.querySelector('canvas');const ctx=canvas.getContext('2d');const source=new Image();source.src='assets/hero/portrait-glasses.webp';const cover=document.createElement('canvas');const coverCtx=cover.getContext('2d');const brush=document.createElement('canvas');const brushCtx=brush.getContext('2d');let dpr=1,radius=143,diameter=286,points=[],last=null,idle=121,ready=false,ambientRunning=false;
  function resize(){const rect=host.getBoundingClientRect();dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);canvas.style.width=`${rect.width}px`;canvas.style.height=`${rect.height}px`;cover.width=canvas.width;cover.height=canvas.height;radius=143*dpr;diameter=Math.ceil(radius*2);brush.width=brush.height=diameter;if(source.complete&&source.naturalWidth){const scale=Math.max(cover.width/source.naturalWidth,cover.height/source.naturalHeight);const w=source.naturalWidth*scale,h=source.naturalHeight*scale,positionX=innerWidth<=640?.32:.5;coverCtx.clearRect(0,0,cover.width,cover.height);coverCtx.drawImage(source,(cover.width-w)*positionX,(cover.height-h)*.44,w,h);ready=true}}
  function ambientReveal(){if(!ready||ambientRunning||idle<120||scrollY>innerHeight*.85||document.hidden)return;ambientRunning=true;const steps=34,y=canvas.height*(innerWidth<=640?.42:.4);for(let i=0;i<steps;i++)setTimeout(()=>{points.push({x:canvas.width*(.25+.5*i/(steps-1)),y:y+Math.sin(i*.45)*radius*.16});if(i===steps-1)ambientRunning=false},i*22)}
  source.onload=()=>{resize();setTimeout(ambientReveal,2400);setInterval(ambientReveal,9000)};new ResizeObserver(resize).observe(host);resize();
  function updateParallax(){const hero=host.closest('.hero'),progress=Math.max(0,Math.min(1,-hero.getBoundingClientRect().top/hero.offsetHeight));host.style.setProperty('--hero-shift',`${progress*Math.min(innerHeight*.075,76)}px`)}
  addEventListener('scroll',updateParallax,{passive:true});updateParallax();
  addEventListener('pointermove',event=>{if(!ready)return;const rect=host.getBoundingClientRect();const x=(event.clientX-rect.left)*dpr,y=(event.clientY-rect.top)*dpr;if(x<-radius||y<-radius||x>canvas.width+radius||y>canvas.height+radius){last=null;return}if(last){const dx=x-last.x,dy=y-last.y,dist=Math.hypot(dx,dy),count=Math.min(Math.ceil(dist/Math.max(radius*.3,1)),60);for(let i=1;i<=count;i++)points.push({x:last.x+dx*i/count,y:last.y+dy*i/count})}else points.push({x,y});last={x,y};idle=0},{passive:true});
  addEventListener('pointerleave',()=>{last=null});
  function stamp(x,y){brushCtx.clearRect(0,0,diameter,diameter);const gradient=brushCtx.createRadialGradient(radius,radius,0,radius,radius,radius);gradient.addColorStop(0,'#fff');gradient.addColorStop(.55,'rgba(255,255,255,.82)');gradient.addColorStop(1,'rgba(255,255,255,0)');brushCtx.globalCompositeOperation='source-over';brushCtx.fillStyle=gradient;brushCtx.fillRect(0,0,diameter,diameter);brushCtx.globalCompositeOperation='source-in';brushCtx.drawImage(cover,x-radius,y-radius,diameter,diameter,0,0,diameter,diameter);ctx.globalCompositeOperation='source-over';ctx.drawImage(brush,x-radius,y-radius)}
  function tick(){const drawing=points.length>0;if(drawing)idle=0;else idle++;if(idle<=120){ctx.globalCompositeOperation='destination-out';ctx.fillStyle=`rgba(0,0,0,${drawing?.016:Math.min(.016+idle*.004,.5)})`;ctx.fillRect(0,0,canvas.width,canvas.height);if(drawing){points.splice(0).forEach(point=>stamp(point.x,point.y))}else if(idle===120)ctx.clearRect(0,0,canvas.width,canvas.height)}requestAnimationFrame(tick)}requestAnimationFrame(tick)
}

const carousel=document.getElementById('project-carousel');
const carouselSlides=[...carousel.querySelectorAll('.carousel-slide')];
const carouselKeys=carouselSlides.map(slide=>slide.dataset.project);
const carouselDots=[...carousel.querySelectorAll('.carousel-dots button')];
let carouselIndex=0;
let dragStartX=0;
let dragDelta=0;
let dragging=false;
let wheelLocked=false;
let pointerSlideIndex=-1;
let suppressPosterClick=false;

function carouselSpacing(){return innerWidth<=640?innerWidth*.62:innerWidth<=1024?innerWidth*.22:Math.min(innerWidth*.17,16.5*parseFloat(getComputedStyle(root).fontSize))}
function carouselOffset(index,position){let value=index-position;const half=carouselSlides.length/2;while(value>half)value-=carouselSlides.length;while(value<-half)value+=carouselSlides.length;return value}
function layoutCarousel(position=carouselIndex){
  const spacing=carouselSpacing();
  carouselSlides.forEach((slide,index)=>{
    const offset=carouselOffset(index,position),distance=Math.min(Math.abs(offset),2.4);
    const scale=1.055-distance*.095;
    const x=offset*spacing;
    const y=distance*1.05*parseFloat(getComputedStyle(root).fontSize);
    const rotateY=offset*-5.5;
    const rotateZ=offset*1.4;
    slide.style.transform=`translate3d(calc(-50% + ${x}px),${y}px,${distance*-38}px) rotateY(${rotateY}deg) rotateZ(${rotateZ}deg) scale(${scale})`;
    slide.style.opacity=String(Math.max(.38,1-distance*.2));
    slide.style.filter=`saturate(${Math.max(.58,1-distance*.14)})`;
    slide.style.zIndex=String(20-Math.round(distance*4));
  });
}

function renderCarouselInfo(animate=true){
  const key=carouselKeys[carouselIndex],data=OTHER_PROJECTS[key],info=document.getElementById('active-project-info');
  document.getElementById('active-project-number').textContent=String(carouselIndex+1).padStart(2,'0');
  document.getElementById('active-project-category').textContent=`${data.category[lang]} · ${data.year}`;
  document.getElementById('active-project-title').textContent=data.title;
  document.getElementById('active-project-description').textContent=data.description[lang];
  document.getElementById('active-project-tech').replaceChildren(...data.tech.map(value=>{const chip=document.createElement('span');chip.textContent=value;return chip}));
  document.getElementById('active-project-actions').replaceChildren(...data.links.map((link,index)=>{const anchor=document.createElement('a');anchor.className=`pill ${index===0?'pill-dark':'pill-outline'}`;anchor.href=link.href;anchor.target='_blank';anchor.rel='noopener';anchor.textContent=linkLabel(link.type);return anchor}));
  if(animate&&!reducedMotion.matches){info.classList.remove('is-changing');void info.offsetWidth;info.classList.add('is-changing');setTimeout(()=>info.classList.remove('is-changing'),450)}
}

function setCarouselIndex(index,animate=true){
  carouselIndex=(index+carouselSlides.length)%carouselSlides.length;
  carouselSlides.forEach((slide,i)=>{const active=i===carouselIndex,data=OTHER_PROJECTS[carouselKeys[i]];slide.classList.toggle('is-active',active);slide.toggleAttribute('aria-current',active);slide.querySelector('.project-poster').setAttribute('aria-label',active?`${data.title} — ${data.links.map(link=>linkLabel(link.type)).join(' / ')}`:data.title)});
  carouselDots.forEach((dot,i)=>dot.classList.toggle('active',i===carouselIndex));
  document.getElementById('carousel-counter').textContent=`${String(carouselIndex+1).padStart(2,'0')} / ${String(carouselSlides.length).padStart(2,'0')}`;
  layoutCarousel();renderCarouselInfo(animate);
}

const primaryProjectLink=data=>data.links.find(link=>link.type==='live')||data.links[0];
carouselSlides.forEach((slide,index)=>slide.querySelector('.project-poster').addEventListener('click',()=>{if(suppressPosterClick)return;if(index===carouselIndex)window.open(primaryProjectLink(OTHER_PROJECTS[carouselKeys[index]]).href,'_blank','noopener');else setCarouselIndex(index)}));
carouselDots.forEach((dot,index)=>dot.addEventListener('click',()=>setCarouselIndex(index)));
document.getElementById('carousel-prev').addEventListener('click',()=>setCarouselIndex(carouselIndex-1));
document.getElementById('carousel-next').addEventListener('click',()=>setCarouselIndex(carouselIndex+1));
carousel.addEventListener('keydown',event=>{if(event.key==='ArrowLeft'){event.preventDefault();setCarouselIndex(carouselIndex-1)}else if(event.key==='ArrowRight'){event.preventDefault();setCarouselIndex(carouselIndex+1)}else if((event.key==='Enter'||event.key===' ')&&event.target===carousel){event.preventDefault();window.open(primaryProjectLink(OTHER_PROJECTS[carouselKeys[carouselIndex]]).href,'_blank','noopener')}});
carousel.addEventListener('pointerdown',event=>{if(event.button!==0||!event.target.closest('.carousel-stage'))return;dragging=true;dragStartX=event.clientX;dragDelta=0;pointerSlideIndex=carouselSlides.findIndex(slide=>slide.contains(event.target));carousel.classList.add('is-dragging');carousel.setPointerCapture(event.pointerId)});
carousel.addEventListener('pointermove',event=>{if(!dragging)return;dragDelta=event.clientX-dragStartX;layoutCarousel(carouselIndex-dragDelta/carouselSpacing())});
function finishDrag(event){if(!dragging)return;dragging=false;carousel.classList.remove('is-dragging');if(carousel.hasPointerCapture(event.pointerId))carousel.releasePointerCapture(event.pointerId);suppressPosterClick=true;setTimeout(()=>suppressPosterClick=false,0);if(event.type==='pointercancel'){layoutCarousel();return}if(Math.abs(dragDelta)>Math.min(72,carouselSpacing()*.22))setCarouselIndex(carouselIndex+(dragDelta<0?1:-1));else if(pointerSlideIndex>=0){if(pointerSlideIndex===carouselIndex)window.open(primaryProjectLink(OTHER_PROJECTS[carouselKeys[pointerSlideIndex]]).href,'_blank','noopener');else setCarouselIndex(pointerSlideIndex)}else layoutCarousel()}
carousel.addEventListener('pointerup',finishDrag);carousel.addEventListener('pointercancel',finishDrag);
carousel.addEventListener('wheel',event=>{const horizontal=Math.abs(event.deltaX)>Math.abs(event.deltaY)||event.shiftKey;if(!horizontal)return;event.preventDefault();if(wheelLocked||Math.abs(event.deltaX||event.deltaY)<8)return;wheelLocked=true;setCarouselIndex(carouselIndex+((event.deltaX||event.deltaY)>0?1:-1));setTimeout(()=>wheelLocked=false,520)},{passive:false});
addEventListener('resize',()=>layoutCarousel());
setCarouselIndex(2,false);

let statsDone=false;
const statsObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting||statsDone)return;statsDone=true;document.querySelectorAll('[data-count]').forEach((el,index)=>{const target=Number(el.dataset.count),decimal=Number(el.dataset.decimal||0),suffix=el.dataset.suffix||'',start=performance.now()+index*90;function count(now){const p=Math.max(0,Math.min(1,(now-start)/1000));const eased=1-(1-p)**3;const raw=target*eased;el.textContent=decimal?(raw/100).toFixed(decimal):`${Math.round(raw)}${suffix}`;if(p<1)requestAnimationFrame(count)}requestAnimationFrame(count)})}),{threshold:.35});statsObserver.observe(document.querySelector('.stats-panel'));

const caseOrder=['kanyolda','sinaru','perfiai','keyco'];
function linkLabel(type){return t(`case.${type}`)}
function renderCase(key){const data=CASE_STUDIES[key],index=caseOrder.indexOf(key);document.getElementById('case-counter').textContent=`${String(index+1).padStart(2,'0')} / 04`;document.getElementById('case-category').textContent=data.category[lang];document.getElementById('case-title').textContent=data.title;document.getElementById('case-summary').textContent=data.summary[lang];const image=document.getElementById('case-image');image.src=data.image;image.alt=data.alt[lang];document.getElementById('case-facts').replaceChildren(...data.facts[lang].map(([label,value])=>{const item=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;item.append(dt,dd);return item}));document.getElementById('case-problem').textContent=data.problem[lang];document.getElementById('case-approach').textContent=data.approach[lang];document.getElementById('case-result').textContent=data.result[lang];document.getElementById('case-decisions').replaceChildren(...data.decisions[lang].map(value=>{const li=document.createElement('li');li.textContent=value;return li}));document.getElementById('case-actions').replaceChildren(...data.links.map(link=>{const a=document.createElement('a');a.href=link.href;a.target='_blank';a.rel='noopener';a.textContent=linkLabel(link.type);return a}));document.getElementById('case-prev').disabled=index===0;document.getElementById('case-next').disabled=index===caseOrder.length-1}
function animateCase(direction=1){if(reducedMotion.matches)return;[document.getElementById('case-category'),document.getElementById('case-title'),document.getElementById('case-summary')].forEach((el,index)=>el.animate([{opacity:0,transform:`translateY(${20+index*8}px)`,filter:'blur(5px)'},{opacity:1,transform:'none',filter:'blur(0)'}],{duration:650,delay:60+index*65,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'}));document.querySelector('.case-visual').animate([{opacity:0,clipPath:`inset(0 ${direction>0?'100%':'0'} 0 ${direction>0?'0':'100%'})`,transform:`translateX(${direction*30}px)`},{opacity:1,clipPath:'inset(0)',transform:'none'}],{duration:800,delay:150,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'})}
function openCase(key,trigger){activeCase=key;caseTrigger=trigger;renderCase(key);dialog.showModal();lock();dialog.scrollTop=0;requestAnimationFrame(()=>animateCase(1))}
function closeCase(){if(!dialog.open)return;dialog.close();activeCase=null;unlock();caseTrigger?.focus({preventScroll:true})}
document.querySelectorAll('[data-open-project]').forEach(button=>button.addEventListener('click',()=>openCase(button.dataset.openProject,button)));dialog.querySelector('.case-close').addEventListener('click',closeCase);dialog.addEventListener('cancel',event=>{event.preventDefault();closeCase()});document.getElementById('case-prev').addEventListener('click',()=>{const key=caseOrder[caseOrder.indexOf(activeCase)-1];if(key){activeCase=key;renderCase(key);dialog.scrollTop=0;requestAnimationFrame(()=>animateCase(-1))}});document.getElementById('case-next').addEventListener('click',()=>{const key=caseOrder[caseOrder.indexOf(activeCase)+1];if(key){activeCase=key;renderCase(key);dialog.scrollTop=0;requestAnimationFrame(()=>animateCase(1))}});

document.getElementById('year').textContent=new Date().getFullYear();
applyLanguage();setupLiquidReveal();startLoader();
